### ISSUE TITLE
add other dotfiles to repository

### ISSUE THREAD

**Issue by vm-wylbur** [adrian-DC/dotfiles#2]
Other dotfiles also benefit from version control: `~/.gitconfig` and `~/.vimrc` are the most obvious candidates. You might find others.

**Comment by adrian-DC** [comment]
Added new vim directory, but I'm not sure what kind of stuff to put on .gitconfig. Any suggestions?

**Comment by vm-wylbur** [comment]
The [`.gitconfig`](https://git-scm.com/docs/git-config) file could move to `dotfiles/git` similar to the `bash` and `vim` work. See the examples section in the link I've added here. There are only a few options, but name, email, and `[core] editor = vim` are all useful. 

also, you might think about using [markdown](https://guides.github.com/features/mastering-markdown/) in your comments here. See the link, it's very helpful.
